### ISSUE TITLE
How to interpret program output?

### ISSUE THREAD

**Issue by sebix** [Oblomov/cltests#1]
I couldn't find any resources explaining the program output, so I open an issue for the missing docs.

Running the program on a GPU with 4GB memory in total gives me this output:

```
$ ./overalloc-migrate
1 platforms found
using platform 0: AMD Accelerated Parallel Processing
2 devices found
using device 0: Pitcairn
will use 268435456 workitems grouped by 64 to process 268435456 elements
will try allocating 4 buffers of 1024MB each to overcommit 3072MB
buffer 0 allocated
buffer 1 allocated
buffer 2 allocated
buffer 3 allocated
testing buffer 1
testing buffer 2
testing buffer 3
main:215: mapping buffer : error -4
```

Does this mean, that 3GB are availbale via OpenCL, or just 1GB? What is meant by `2 devices found`?
I guess the error means, overcommitting has failed.

**Comment by Oblomov** [comment]
`2 devices found`: the AMD platform supports both AMD/ATI GPUs and x86-compatible CPUs, so it exposes two devices on your machine (the GPU and the CPU).

The driver reports 3GB of memory on the GPU, so the programs tries overallocation by using 4 buffers of 1GB each.

And yes, overcommitting fails, which is in fact expected since sadly no platform I know of actually implements the possibility to swap buffers out (which is otherwise supported by the specifications).
